import * as path from "node:path";
import { describe, expect, it } from "vitest";

import {
  buildRerunCommand,
  formatSize,
  totalProcessedSizeForEntry,
  totalProcessedSizeForResult,
} from "../src/runner/reporting.js";
import type { RerunCommandOptions } from "../src/runner/reporting.js";
import type { ImageForgeEntry } from "../src/types.js";

function rerunOptions(overrides: Partial<RerunCommandOptions> = {}): RerunCommandOptions {
  return {
    commandName: "imageforge",
    directoryArg: "images",
    outputPath: path.join(process.cwd(), "imageforge.json"),
    formats: ["webp"],
    quality: 80,
    blur: true,
    blurSize: 4,
    widths: null,
    useCache: true,
    forceOverwrite: false,
    outDir: null,
    dryRun: false,
    includePatterns: [],
    excludePatterns: [],
    concurrency: 4,
    ...overrides,
  };
}

describe("runner reporting", () => {
  it("builds a minimal reproducible command with workspace-relative paths", () => {
    expect(buildRerunCommand(rerunOptions(), process.cwd())).toBe(
      "imageforge images --output imageforge.json --formats webp --quality 80 --blur-size 4 --concurrency 4"
    );
  });

  it("uses an explicit project-local command prefix without quoting it as one executable", () => {
    expect(
      buildRerunCommand(
        rerunOptions({ commandPrefix: ["pnpm", "exec", "imageforge"] }),
        process.cwd()
      )
    ).toBe(
      "pnpm exec imageforge images --output imageforge.json --formats webp --quality 80 --blur-size 4 --concurrency 4"
    );
  });

  it("preserves every behavior-affecting option and shell-quotes unsafe arguments", () => {
    const outputDir = path.join(process.cwd(), "generated images");
    const command = buildRerunCommand(
      rerunOptions({
        directoryArg: "source images",
        outputPath: path.join(process.cwd(), "manifests", "image forge.json"),
        formats: ["webp", "avif"],
        quality: 61,
        blur: false,
        blurSize: 7,
        widths: [320, 640],
        useCache: false,
        forceOverwrite: true,
        outDir: outputDir,
        dryRun: true,
        includePatterns: ["hero $1.jpg", "assets/**"],
        excludePatterns: ["draft `old`.png"],
        concurrency: 2,
      }),
      outputDir
    );

    expect(command).toContain('"source images"');
    expect(command).toContain('--output "manifests/image forge.json"');
    expect(command).toContain("--formats webp,avif --quality 61 --blur-size 7 --concurrency 2");
    expect(command).toContain("--no-blur --widths 320,640 --no-cache --force-overwrite");
    expect(command).toContain('--include "hero \\$1.jpg" --include "assets/**"');
    expect(command).toContain('--exclude "draft \\`old\\`.png"');
    expect(command).toContain('--out-dir "generated images" --dry-run');
  });

  it.each([
    [0, "0B"],
    [1023, "1023B"],
    [1024, "1.0KB"],
    [1536, "1.5KB"],
    [1024 * 1024, "1.0MB"],
  ])("formats %i bytes as %s", (bytes, expected) => {
    expect(formatSize(bytes)).toBe(expected);
  });

  it("deduplicates the selected responsive output when totaling generated bytes", () => {
    const entry: ImageForgeEntry = {
      width: 800,
      height: 400,
      aspectRatio: 2,
      blurDataURL: "",
      originalSize: 100,
      hash: "hash",
      outputs: { webp: { path: "hero.w640.webp", size: 40 } },
      variants: {
        webp: [
          { width: 320, height: 160, path: "hero.w320.webp", size: 20 },
          { width: 640, height: 320, path: "hero.w640.webp", size: 40 },
        ],
      },
    };

    expect(totalProcessedSizeForEntry(entry)).toBe(60);
    expect(
      totalProcessedSizeForResult({
        file: "hero.jpg",
        width: entry.width,
        height: entry.height,
        aspectRatio: entry.aspectRatio,
        blurDataURL: entry.blurDataURL,
        originalSize: entry.originalSize,
        outputs: entry.outputs,
        variants: entry.variants,
      })
    ).toBe(60);
  });
});
