name: Bug report
description: Report a reproducible bug
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please include enough detail to reproduce it.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug and expected behavior.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Provide a minimal reproduction, including command and input files.
      placeholder: |
        1. Run `imageforge ...`
        2. Observe ...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: ImageForge version
      placeholder: 0.1.0
    validations:
      required: true

  - type: input
    id: node
    attributes:
      label: Node.js version
      placeholder: 22.x
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - macOS
        - Linux
        - Windows
        - Other
    validations:
      required: true
